//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsaatMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsaatMalzemeleriEntities : DbContext
    {
        public InsaatMalzemeleriEntities()
            : base("name=InsaatMalzemeleriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cement> Cements { get; set; }
        public virtual DbSet<Steel> Steels { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
